-- MySQL Script generated by MySQL Workbench
-- qua 26 jun 2024 23:04:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u134451290_bd_xoxo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u134451290_bd_xoxo` ;

-- -----------------------------------------------------
-- Schema u134451290_bd_xoxo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u134451290_bd_xoxo` ;
USE `u134451290_bd_xoxo` ;

-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_departamento` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_departamento` (
  `id_tb_departamento` INT NOT NULL AUTO_INCREMENT,
  `nome_tb_departamento` VARCHAR(100) NOT NULL,
  `descricao_tb_departamento` VARCHAR(255) NOT NULL,
  `data_cadastro_tb_departamento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tb_departamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_grade` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_grade` (
  `id_tb_grade` INT NOT NULL AUTO_INCREMENT,
  `tipo_tb_grade` ENUM('1', '2') NOT NULL,
  `pp_tb_grade` INT NULL DEFAULT '0',
  `p_tb_grade` INT NULL DEFAULT '0',
  `m_tb_grade` INT NULL DEFAULT '0',
  `g_tb_grade` INT NULL DEFAULT '0',
  `gg_tb_grade` INT NULL DEFAULT '0',
  `34_tb_grade` INT NULL DEFAULT '0',
  `36_tb_grade` INT NULL DEFAULT '0',
  `38_tb_grade` INT NULL DEFAULT '0',
  `40_tb_grade` INT NULL DEFAULT '0',
  `42_tb_grade` INT NULL DEFAULT '0',
  `44_tb_grade` INT NULL DEFAULT '0',
  `46_tb_grade` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_tb_grade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_produto` (
  `id_tb_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_tb_produto` VARCHAR(100) NOT NULL,
  `descricao_tb_produto` VARCHAR(255) NOT NULL,
  `custo_tb_produto` FLOAT NOT NULL,
  `varejo_tb_produto` FLOAT NOT NULL,
  `atacado_tb_produto` FLOAT NOT NULL,
  `grade_tb_produto` ENUM('1', '2') NOT NULL DEFAULT '1',
  `id_departamento_tb_produto` INT NOT NULL,
  `tb_grade_id_tb_grade` INT NOT NULL,
  `img1_tb_produto` VARCHAR(255) NOT NULL,
  `img2_tb_produto` VARCHAR(255) NOT NULL,
  `img3_tb_produto` VARCHAR(255) NOT NULL,
  `premium_tb_produto` ENUM('0', '1') NOT NULL,
  `visualizar_tb_produto` ENUM('1', '0') NOT NULL,
  PRIMARY KEY (`id_tb_produto`),
  INDEX `fk_tb_produto_1_idx1` (`id_departamento_tb_produto` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_grade1_idx` (`tb_grade_id_tb_grade` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_1`
    FOREIGN KEY (`id_departamento_tb_produto`)
    REFERENCES `u134451290_bd_xoxo`.`tb_departamento` (`id_tb_departamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_produto_tb_grade1`
    FOREIGN KEY (`tb_grade_id_tb_grade`)
    REFERENCES `u134451290_bd_xoxo`.`tb_grade` (`id_tb_grade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_usuario` (
  `id_tb_usuario` INT NOT NULL AUTO_INCREMENT,
  `cpf_tb_usuario` VARCHAR(11) NULL,
  `nome_tb_usuario` VARCHAR(255) NOT NULL,
  `email_tb_usuario` VARCHAR(255) NOT NULL,
  `contato_tb_usuario` VARCHAR(20) NOT NULL COMMENT '(00) 00000-0000',
  `senha_tb_usuario` VARCHAR(45) NOT NULL,
  `data_cadastro_tb_usuario` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_nascimento_tb_usuario` DATE NULL,
  PRIMARY KEY (`id_tb_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_endereco` (
  `id_tb_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua_tb_endereco` VARCHAR(255) NOT NULL,
  `num_tb_endereco` VARCHAR(20) NOT NULL,
  `bai_tb_endereco` VARCHAR(45) NOT NULL,
  `cid_tb_endereco` VARCHAR(45) NOT NULL,
  `est_tb_endereco` VARCHAR(45) NOT NULL,
  `id_usuario_tb_endereco` INT NOT NULL,
  PRIMARY KEY (`id_tb_endereco`),
  INDEX `fk_tb_endereco_tb_usuario1_idx` (`id_usuario_tb_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_endereco_tb_usuario1`
    FOREIGN KEY (`id_usuario_tb_endereco`)
    REFERENCES `u134451290_bd_xoxo`.`tb_usuario` (`id_tb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_venda` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_venda` (
  `id_tb_venda` INT NOT NULL AUTO_INCREMENT,
  `entrega_tb_venda` ENUM('0', '1') NOT NULL COMMENT '0 = Não\n1 = Sim',
  `tx_entrega_tb_venda` FLOAT NULL,
  `pagamento_entrega_tb_venda` ENUM('0', '1', '2') NOT NULL COMMENT '0 = Pix\n1 = Espécie\n2 = Crédito/Débito',
  `status_tb_venda` ENUM('0', '1', '2', '3', '4', '5') NOT NULL COMMENT '0 = Aguardando\n1 = Separado\n2 = Em rota\n3 = Entregue/Finalizado\n4 = Cancelado pelo Vendedor\n5 = Cancelado pelo Comprador',
  `data_cadastro_tb_venda` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_usuario_tb_venda` INT NOT NULL,
  `endereco_entrega_tb_venda` VARCHAR(255) NULL,
  `cancelamento_tb_venda` VARCHAR(255) NULL,
  `taxa_desconto_tb_venda` INT NULL,
  PRIMARY KEY (`id_tb_venda`),
  INDEX `fk_tb_venda_tb_usuario1_idx` (`id_usuario_tb_venda` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_usuario1`
    FOREIGN KEY (`id_usuario_tb_venda`)
    REFERENCES `u134451290_bd_xoxo`.`tb_usuario` (`id_tb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_produto_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_produto_venda` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_produto_venda` (
  `id_tb_produto_venda` INT NOT NULL AUTO_INCREMENT,
  `id_venda_tb_produto_venda` INT NOT NULL,
  `id_produto_tb_produto_venda` INT NOT NULL,
  `quantidade_tb_produto_venda` INT NOT NULL,
  `grade_tb_produto_venda` VARCHAR(255) NOT NULL,
  INDEX `fk_tb_produto_venda_tb_venda1_idx` (`id_venda_tb_produto_venda` ASC) VISIBLE,
  INDEX `fk_tb_produto_venda_tb_produto1_idx` (`id_produto_tb_produto_venda` ASC) VISIBLE,
  PRIMARY KEY (`id_tb_produto_venda`),
  CONSTRAINT `fk_tb_produto_venda_tb_venda1`
    FOREIGN KEY (`id_venda_tb_produto_venda`)
    REFERENCES `u134451290_bd_xoxo`.`tb_venda` (`id_tb_venda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_produto_venda_tb_produto1`
    FOREIGN KEY (`id_produto_tb_produto_venda`)
    REFERENCES `u134451290_bd_xoxo`.`tb_produto` (`id_tb_produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_cupom` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_cupom` (
  `id_tb_cupom` INT NOT NULL AUTO_INCREMENT,
  `prefixo_tb_cupom` VARCHAR(45) NOT NULL,
  `status_tb_cupom` ENUM('0', '1') NULL DEFAULT '1',
  `desconto_tb_cupom` INT NOT NULL,
  `data_cadastro_tb_cupom` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tb_cupom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u134451290_bd_xoxo`.`tb_item_cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u134451290_bd_xoxo`.`tb_item_cupom` ;

CREATE TABLE IF NOT EXISTS `u134451290_bd_xoxo`.`tb_item_cupom` (
  `id_tb_item_cupom` INT NOT NULL AUTO_INCREMENT,
  `status_tb_item_cupom` ENUM('0', '1') NULL DEFAULT '1',
  `id_cupom_tb_item_cupom` INT NOT NULL,
  `id_usuario_tb_item_cupom` INT NOT NULL,
  `data_cadastro_tb_item_cupom` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tb_item_cupom`),
  INDEX `fk_tb_item_cupom_tb_cupom1_idx` (`id_cupom_tb_item_cupom` ASC) VISIBLE,
  INDEX `fk_tb_item_cupom_tb_usuario1_idx` (`id_usuario_tb_item_cupom` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_cupom_tb_cupom1`
    FOREIGN KEY (`id_cupom_tb_item_cupom`)
    REFERENCES `u134451290_bd_xoxo`.`tb_cupom` (`id_tb_cupom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_item_cupom_tb_usuario1`
    FOREIGN KEY (`id_usuario_tb_item_cupom`)
    REFERENCES `u134451290_bd_xoxo`.`tb_usuario` (`id_tb_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
